### ISSUE TITLE
Rock for lua SNMP

### ISSUE THREAD

**Issue by 4mig4** [hleuwer/luasnmp#2]
Is it possible to make a `rock` for `luarocks` for `luasnmp` ? 

- <https://luarocks.org/>

**Comment by hleuwer** [comment]
It is certainly possible. However, I'm neither a Luarocks expert nor do I have time to work on this. Sorry!

**Comment by nodecentral** [comment]
Hi, (appreciate it’s not a priority and no time etc) I just wanted to upvote that I’d love to see this available via Luarocks too,

**Comment by hleuwer** [comment]
Sorry for the very late reply. I didn't work on or with LuaSNMP for a couple of years. I generated a rockspec for LuaSNMP recently. I works on my MAC with Lua 5.4. I didn't test other platforms or Lua versions. However, since I didn't changed the source code, I expect it will also work on other platforms and Lua versions.
Feedback of course welcome :-).

**Comment by hleuwer** [comment]
I close this issues.

**Comment by 4mig4** [comment]
Thanks :)
